name: "Update AUR"

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  aur:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ouuan'
    strategy:
      fail-fast: false
      matrix:
        pkgname: ["lean-community", "python-mathlibtools"]

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Check PKGBUILD
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: pkgbuild
          pkgname: ${{ matrix.pkgname }}

      - name: Check .SRCINFO
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: srcinfo
          pkgname: ${{ matrix.pkgname }}

      - name: Clone AUR and update
        run: |
          sudo git clean -dfx
          git clone ssh://aur@aur.archlinux.org/${{ matrix.pkgname }}.git ../aur
          rm ../aur/* || true
          cp ${{ matrix.pkgname }}/* ${{ matrix.pkgname }}/.SRCINFO ../aur
          cd ../aur
          git config user.name "Yufan You"
          git config user.email "ouuansteve@gmail.com"
          git add -A
          git diff-index @ --exit-code --quiet || git commit -m "Update from GitHub Actions: ${{ github.event.head_commit.message }}

          https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          git push
