name: "Update AUR"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"

jobs:
  aur:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ouuan'
    strategy:
      fail-fast: false
      matrix:
        pkgname: ["lean-community", "python-mathlibtools"]

    steps:
      - uses: actions/checkout@v2

      - name: Check PKGBUILD
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: pkgbuild
          pkgname: ${{ matrix.pkgname }}

      - name: Check .SRCINFO
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: srcinfo
          pkgname: ${{ matrix.pkgname }}

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.1.0
        with:
          pkgname: ${{ matrix.pkgname }}
          pkgbuild: ${{ matrix.pkgname }}/PKGBUILD
          commit_username: Yufan You
          commit_email: ouuansteve@gmail.com
          commit_message: "Update from GitHub Actions: ${{ github.event.head_commit.message }}\n\nhttps://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          allow_empty_commits: false
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
